theme: minima
title: Vinayak Gajjewar
author: Vinayak Gajjewar
email: vinayakgajjewar@gmail.com
email_show: vinayakgajjewar [at] gmail [dot] com
github_username: vinayakgajjewar
linkedin_username: vinayak-gajjewar-464806195
